# Generated by Django 2.0.7 on 2020-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=255)),
                ('pusbishedAt', models.CharField(max_length=255)),
            ],
        ),
    ]
