# Generated by Django 2.0.7 on 2020-08-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20200810_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsapp',
            table='NewsApp',
        ),
    ]
